version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: auction_postgres
    restart: always
    environment:
      POSTGRES_USER: auction
      POSTGRES_PASSWORD: auction
      POSTGRES_DB: auctiondb
    ports:
      - "5432:5432"
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
    networks:
      - auction-net

  backend:
    build: .
    container_name: backend-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - postgres
    restart: always
    networks:
      - auction-net

networks:
  auction-net:
    driver: bridge
